### ISSUE TITLE
Broken link to internal UCAR site

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-cookoff-2023#10]
We have a link-checker failure for this site:
https://github.com/ProjectPythia/pythia-cookoff-2023/actions/runs/4727436872/jobs/8388041035#step:7:61

It looks like the link in question is https://sundog.ucar.edu/Interact/Pages/Content/Document.aspx?id=5645,
which directs to a UCAR login page.

It's supposed to be a link to information about the UCAR shuttle service. @jukent would you be able to find a relevant link to an open web page about the UCAR shuttle?

**Comment by jukent** [comment]
Oh good point. From that page, there is a PDF of the shuttle schedule. Are you able to access this link: https://drive.google.com/file/d/13b9338X923Fa8gJ5iEEH1y2XBavIRl1q/view

**Comment by jukent** [comment]
Oh this link is probably best: https://wiki.ucar.edu/display/DIME/Visitor+Information

Can you double check that you don't have to sign in to access it? (Since I'm already signed in)

**Comment by brian-rose** [comment]
> Oh this link is probably best: https://wiki.ucar.edu/display/DIME/Visitor+Information
> 
> Can you double check that you don't have to sign in to access it? (Since I'm already signed in)

Works for me!

**Comment by brian-rose** [comment]
> Oh this link is probably best: https://wiki.ucar.edu/display/DIME/Visitor+Information
> 
> Can you double check that you don't have to sign in to access it? (Since I'm already signed in)

Works for me!
